name: Update ytdl-core package

on: workflow_dispatch

jobs:
  bump-ytdl:
    name: Update ytdl-core package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - run: git config --global user.name ${{ secrets.GH_USERNAME }}
      - run: git config --global user.email ${{ secrets.GH_EMAIL }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm install
      - run: npm uninstall ytdl-core
      - run: npm install ytdl-core
      - run: git commit -a -m "[GIT-ACTION] Updated ytdl-core version"