name: tagged-release

# on: workflow_dispatch

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install NPM dependencies
        run: npm ci

      - name: NPM install build tools
        run: npm install pkg

      - name: Build project assets
        run: npm run build

      - name: Install zip git-action package
        uses: montudor/action-zip@v1

      - name: Zip windows build
        run:  zip -qq -r win${{env.RELEASE_VERSION}}.zip . -i build/youtube-scissors-win config.json
        working-directory: build