name: Tagged & Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version Number
        default: v1.0.0
        required: true

jobs:
  build-to-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - run: git config --global user.name ${{ secrets.GH_USERNAME }}
      - run: git config --global user.email ${{ secrets.GH_EMAIL }}
      - run: git tag ${{ github.event.inputs.version }}
      - run: git push origin --tags

      - name: Install NPM dependencies
        run: npm ci

      - name: NPM install build tools
        run: npm install pkg

      - name: Building executables
        run: npm run build

      - name: Install zip git-action package
        uses: montudor/action-zip@v1

      - name: Zip windows build
        run: |
          mv ./build/youtube-scissors-cli-win.exe .
          zip -qq -r win-${{ github.event.inputs.version }}.zip . -i youtube-scissors-cli-win.exe config.json

      - name: Zip macos build
        run: | 
          mv ./build/youtube-scissors-cli-macos .
          zip -qq -r macos-${{ github.event.inputs.version }}.zip . -i youtube-scissors-cli-macos config.json

      - name: Zip linux build
        run: |
          mv ./build/youtube-scissors-cli-linux .
          zip -qq -r linux-${{ github.event.inputs.version }}.zip . -i youtube-scissors-cli-linux config.json

      - name: Release build
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GIT_TOKEN }}"
          prerelease: false
          files: |
            ./linux-${{ github.event.inputs.version }}.zip
            ./macos-${{ github.event.inputs.version }}.zip
            ./win-${{ github.event.inputs.version }}.zip
