name: "Testing Node.js"

on: [pull_request, workflow_dispatch]

jobs:
  Test:
    name: Testing Node.js Functions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      
      - name: "Install All Packages"
        run: npm install
      
      - name: "Run Test"
        run: npm test
