name: "Test Build"

on: [pull_request, workflow_dispatch]

jobs:
  Test:
    name: Testing Build to Executables
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      
      - name: Install NPM dependencies
        run: npm ci

      - name: NPM install build tools
        run: npm install pkg

      - name: Building executables
        run: npm run build