name: "Test Build"

on: [pull_request, workflow_dispatch]

jobs:
  Test:
    name: Testing Build to Executables
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      
      # Applying https://stackoverflow.com/questions/58423725/github-actions-not-working-after-npm-start
      - name: Install and Run Build
        run: |
          npm ci
          npm install pkg
          npm run build
        env:
          CI: true
