name: "Test Build"

on: [pull_request, push]

jobs:
  Test:
    name: Testing Build to Executables
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
         
      # Using https://courses.cs.northwestern.edu/394/guides/github-actions-setup.php
      - run: npm install
      - run: npm run build
