name: "Testing Node.js"

on: pull_request

jobs:
  Test:
    name: Testing Node.js Functions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      
      - name: "Install All Packages"
        run: npm ci
      
      - name: "Run Test"
        run: npm run test
